/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:219c45ef-4a04-4ed3-8764-71d57481d4fb",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_2XkeFP7XC",
    "aws_user_pools_web_client_id": "51j92c3qialpuc87togg3h6ur5",
    "oauth": {},
    "aws_mobile_analytics_app_id": "d5903e53d8fc4ef193a1a8762b0ec1dd",
    "aws_mobile_analytics_app_region": "us-east-1"
};


export default awsmobile;
